-- Drop and recreate viewed_payment_receipts table with TEXT types
DROP TABLE IF EXISTS public.viewed_payment_receipts CASCADE;

-- Create table with TEXT types
CREATE TABLE public.viewed_payment_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_viewed_payment_receipts_receipt_id ON public.viewed_payment_receipts(receipt_id);
CREATE INDEX idx_viewed_payment_receipts_user_id ON public.viewed_payment_receipts(user_id);

-- Enable RLS
ALTER TABLE public.viewed_payment_receipts ENABLE ROW LEVEL SECURITY;

-- RLS Policy
CREATE POLICY "Allow full access to viewed_payment_receipts" ON public.viewed_payment_receipts
  FOR ALL USING (true);
