-- Payment checker notification persistence fix
-- Run this in Supabase SQL editor.

BEGIN;

-- 1) Create/ensure viewed receipt tracking table
CREATE TABLE IF NOT EXISTS public.viewed_payment_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT viewed_payment_receipts_unique UNIQUE (receipt_id, user_id)
);

-- 2) Helpful indexes for unread count lookups
CREATE INDEX IF NOT EXISTS idx_viewed_payment_receipts_receipt_id
  ON public.viewed_payment_receipts (receipt_id);
CREATE INDEX IF NOT EXISTS idx_viewed_payment_receipts_user_id
  ON public.viewed_payment_receipts (user_id);
CREATE INDEX IF NOT EXISTS idx_viewed_payment_receipts_viewed_at
  ON public.viewed_payment_receipts (viewed_at DESC);

-- 3) Enable RLS and authenticated read/insert (safe if app later stops using service role)
ALTER TABLE public.viewed_payment_receipts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'viewed_payment_receipts'
      AND policyname = 'viewed_receipts_select_own'
  ) THEN
    CREATE POLICY viewed_receipts_select_own
      ON public.viewed_payment_receipts
      FOR SELECT
      TO authenticated
      USING (auth.uid()::text = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'viewed_payment_receipts'
      AND policyname = 'viewed_receipts_insert_own'
  ) THEN
    CREATE POLICY viewed_receipts_insert_own
      ON public.viewed_payment_receipts
      FOR INSERT
      TO authenticated
      WITH CHECK (auth.uid()::text = user_id);
  END IF;
END $$;

COMMIT;
